services:
  - type: web
    name: commentbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PORT
        value: 5000
      - key: HOST
        value: 0.0.0.0
